#!/bin/bash
export home=/home/hohla
export MT=$home'/.mt4/dosdevices/c:/'
if [ ! -d $home/Desktop/CSV_Files ]; then mkdir -p $home/Desktop/CSV_Files; fi
SYMBOLS=(EUR USD USD2 DARW) # названия папок/ярлыков
for index in ${!SYMBOLS[*]}
do
 SYM=${SYMBOLS[$index]}
 echo $SYM ': copy csv files'
cp $home/Desktop/CSV_Files/'#.csv' $home/.mt4/dosdevices/c:/$SYM/MQL4/Files/
cp $home/.mt4/dosdevices/c:/$SYM/MQL4/Files/MatLab* $home/Desktop/CSV_Files/MatLab$SYM.csv
done
